from cancer.pipeline.data_ingestion_pipeline import DataIngestionTrainingPipeline
from cancer.pipeline.prepare_base_model_pipeline import PrepareBaseModelTrainingPipeline
from cancer.pipeline.model_trainer_pipeline import ModelTrainingPipeline
from cancer.pipeline.model_evaluation_pipeline import EvaluationPipeline